os: linux
language: python
dist: xenial
jobs:
  include:
    - name: Minimum NEP 029 versions
      python: 3.6
      env: NUMPY_VER=1.15
    # Versions with latest numpy
    - python: 3.6
    - python: 3.7
    - python: 3.8

services: xvfb

addons:
  apt:
    packages:
    - gfortran

before_install:
  - if [ -z ${NUMPY_VER} ]; then
      # Make sure travis uses latest numpy, not pre-installed version
      pip install -q numpy --upgrade;
    else
      pip install -q numpy==$NUMPY_VER;
    fi
  - pip install "matplotlib<3.3"
  - pip install pytest-cov
  - pip install pytest-flake8
  - pip install coveralls
  - pip install future

install:
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0

script:
  - pytest -vs --flake8 --cov=sami2py/

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
